### ISSUE TITLE
Ventura support only?

### ISSUE THREAD

**Issue by jaffacakerhubarb** [Rugged-Apps/InventoryWatch-Feedback#1]
Just tried to update to v2.0 of InventoryWatch, but it looks like the app only supports macOS 13.0 (Ventura) now. Is this deliberate?

**Comment by worthbak** [comment]
That's correct - my apologies, we failed to list the system requirements on our homepage. I'll make that change shortly.

**Comment by jaffacakerhubarb** [comment]
That's a shame, I'd have thought a lot of people eyeing new devices might well be limited to say Monterey, but I'm sure there's a good reason coding wise.

I've had a look on another Mac of mine running Ventura and it looks great, nice job!

**Comment by worthbak** [comment]
Thanks - we really appreciate your feedback! 

For some background, InventoryWatch for macOS is built using SwiftUI, and Apple made some substantial improvements to SwiftUI on the Mac in Ventura. Prior to those updates, it was pretty difficult to build anything complex using SwiftUI on the Mac (hence InventoryWatch 1.0's limitations). So, for the updated app, we decided to require macOS 13.0 Ventura, and should stick with that base version-requirement for the foreseeable future. 

If you need access on older Macs (or any device with a modern web browser, including your phone), [InventoryWatch is also now available on the web](https://inventorywatch.app) 🥳 let me know if you have any questions about that. Cheers!
