### ISSUE TITLE
Testing notification on Web app

### ISSUE THREAD

**Issue by YourKalamity** [Rugged-Apps/InventoryWatch-Feedback#5]
Hello I got the subscription since I don't have access to a Mac and wanted to test the email notification.

I tried to setup the search to point to a device I know is definitely in stock at my local store (an iPhone 14 - with the preferred variant set to the 128GB Purple). This was indeed in stock, but I did not receive any email to notify me of this. I checked all the folders of my inbox, including spam, and I have not received anything.

Does this email only get sent if there is a change?

**Comment by worthbak** [comment]
Hi! Thanks for subscribing!

Here's some info that should help: first, make sure that you’ve selected preferred models for your searches - inventory notifications are only sent out when inventory for preferred models are found, so please ensure that you’ve selected at least one for your searches.

Second, inventory notifications are only sent out when we discover an in-stock model that was previously out of stock. So, after you’ve correctly configured a search, InventoryWatch won’t actually send any notifications until we find inventory for a preferred model that has just become available at a nearby store.

If you’ve configured a search with preferred models, and noticed that relevant inventory has appeared without your being notified, please reach out to customer support (support@inventorywatch.app), as there may be an issue with delivering emails or SMS messages to your account.

**Comment by YourKalamity** [comment]
Great thank you for your fast resposne!
Is there a way to upgrade to the SMS tier without paying for the full amount again (i.e just the difference)

**Comment by worthbak** [comment]
Sure thing! Just send an email to support@inventorywatch.app and note the email address on your account, and we'll get you a prorated upgrade.

**Comment by YourKalamity** [comment]
Gotcha, thank you!
