### ISSUE TITLE
Improvement: Macbook Pro M3 Support?

### ISSUE THREAD

**Issue by christoph-kluge** [Rugged-Apps/InventoryWatch-Feedback#9]
Do you plan to add to add Macbook Pro M3 Models to the preferred list?

<img width="333" alt="Screenshot 2023-11-08 at 09 39 18" src="https://github.com/Rugged-Apps/InventoryWatch-Feedback/assets/1446269/5bdc88e6-cb27-45ea-8216-ac9e73f678af">

**Comment by worthbak** [comment]
M3 MacBook Pro support will be added later today. Apologies for the delay!

**Comment by worthbak** [comment]
InventoryWatch was just updated to support the new M3 MacBook Pros - you may need to restart the app or reload the webpage (inventorywatch.app) to see the new products. Thanks, and let me know if you have any issues!

**Comment by christoph-kluge** [comment]
That was fast! Thank you so much 🙇 Sidenote: It seems #8 is not crashing anymore, as the ProductType dissapeared.

Another question: How does the "Preferred Models"-filter on the right side work? Not all models are reflected in this list.

As an example:
- 14in M3 Max - All 96G selections are missing
- 14in M3 Max - All 128G selections are missing

It feels like it's an unified diff from all available apple stores BUT the two red-marked models doesn't appear at all in the list.

Can you share some insights how the preferred models list is generated? 🔮 At least my preferred model is not there 😢 

<img width="1086" alt="Screenshot 2023-11-09 at 08 55 03" src="https://github.com/Rugged-Apps/InventoryWatch-Feedback/assets/1446269/e20394f4-1d96-461a-bd5c-17d01589f137">

**Comment by worthbak** [comment]
Sure thing! It's actually quite simple: the list of preferred models contains all of the configurations that Apple is known to carry in-stores. 

Certain SOC/RAM/SSD configs are manufactured for sale in-stores (and, as such, are assigned a part number, like `MU8D3`, which is a high-end 14in M3 Max (16/40) with 64GB RAM and 2TB SSD). Only those designated configs are listed as preferred models in InventoryWatch, as they are the only configs that will be available for purchase in Apple Stores. All other configs (ex. 14in M3 Max (16/40) with 128GB RAM and 8TB SSD) are build-to-order only, and must be ordered and shipped via their online store. 

Does that make sense? It is a bit of a bummer that they don't carry more MacBook Pro configurations in-stores (especially on the higher-end), but that's what they've chosen to do.

**Comment by christoph-kluge** [comment]
Accodring to your answer I'll order my configuration now online because it will never hit the stores. Sad that I realised it just now and not some days earlier! 😆 

Mabye It's worth adding it to the FAQ as "Why is my Preferred Model not listed" 🤔 

I'm going to close this issue. M3 support works fine now 👍
